import { chromium } from "playwright";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const dir = dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch();
const pg = await browser.newPage({ viewport: { width: 1220, height: 1240 }, deviceScaleFactor: 2 });
await pg.goto("file://" + resolve(dir, "partner-sticker.html"), { waitUntil: "networkidle" });
await pg.waitForTimeout(1500);
const card = (await pg.$(".card")) || (await pg.$("body"));
await card.screenshot({ path: resolve(dir, "partner-sticker.png") });
await browser.close();
console.log("re-rendered");
